name: TOML linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install taplo
        run: cargo install taplo-cli
      
      - name: Run taplo lint
        run: taplo lint *.conf
